#!/usr/bin/expect
#Generate ssh pair key by mr.zhou
if { $argc != 2 } {
 send_user "Usage: username timeout\n"
 exit 1
}

set username [lindex $argv 0]
set timeout [lindex $argv 1]

spawn /bin/su - $username
expect {
       "$" {send "/usr/bin/ssh-keygen -t dsa\r"}
}
expect {
       "Enter file in which to save the key" {send "\r";exp_continue}
       "Enter passphrase" {send "\r";exp_continue}
       "Enter same passphrase again:" {send "\r";exp_continue}
}
expect eof
exit
